### ISSUE TITLE
Clarify whether keys and values must be strings

### ISSUE THREAD

**Issue by bradh** [sozip/keyvaluepairs-spec#1]
The spec makes it clear that the `kvN_key_text` and `kvN_val_text` are `byte[]` and are UTF-8 encoded. However since the scope is

>  to be able to encode arbitrary key-value pairs of metadata associated with a file within a ZIP

it might be useful to encode other data (e.g. an IEEE double or an image). 

If the data really does need to be text, that should be in the scope.

**Comment by rouault** [comment]
Thanks for the comment!

> If the data really does need to be text, that should be in the scope.

you need to keep in mind that the whole amount of extra field content (this spec + other extra field) is limited to 64 KB per file (due to the total length of the extra field being encoded on a uint16), so storing images is going to be difficult, unless it is really small.
As far as other smallish data, I'd say their text representation should be favored.

Originally I only needed to have an extension to store Content-Type, but I felt it could be slightly generalized to any key/value text pairs. So my current inclination would be indeed to clarify the scope to indicate that. If you include other data types, you'd also need to have some enumeration storing it.

**Comment by bradh** [comment]
I think restricting this to text is reasonable.
